### ISSUE TITLE
LocationCriterionService issue

### ISSUE THREAD

**Issue by phpfreak6** [Edujugon/laravel-google-ads#28]
![package error](https://user-images.githubusercontent.com/5575735/44443734-eeb24b00-a5f6-11e8-86ce-075b142e5018.PNG)

I am getting above error While I am using LocationCriterionService.
 Also How can I retrieve data in array format from the service request . It provided with protected objects.

**Comment by Edujugon** [comment]
Hi @phpfreak6 ,
Have you tried to remove the `getEntries()` method and see what the result is?

**Comment by Edujugon** [comment]
So basically comment that line in red amd uncomment the below line

**Comment by phpfreak6** [comment]
Yes, I did that.  Also how can I get data from the protected objects?

**Comment by Edujugon** [comment]
Well, that's actually out of this package scope but if they are protected it should be for any reason. I would first check if there is access to those props via method in that object. Otherwise if you really need to get access to those values, you may try ReflectionClass.

Here is a handy method to get those prop values:

```php
function accessProtected($obj, $prop) {
  $reflection = new ReflectionClass($obj);

  $property = $reflection->getProperty($prop);
  $property->setAccessible(true);

  return $property->getValue($obj);
}
```

**Comment by Edujugon** [comment]
Hi @phpfreak6 ,
I'm closing this issue since I guess you had enough information with my previous message. Feel free to reopen it again if face any further issue
