### ISSUE TITLE
QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED

### ISSUE THREAD

**Issue by discovery-mark** [Edujugon/laravel-google-ads#37]
Hi,

We're using a test developer token (from a production account as per Google's requirements).

We're getting the following response: QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED

We're trying to query a test account, as we're using a developer token which only has test permissions.

Our env is set to test, and all of the auth has been completed.

We're wondering if the query is still being sent in production mode, but we can't find any evidence to suggest this. If we run the getEnv() function, it tells us it is in test mode.

Is there something we are missing? Is there anyway we can check if the query is definitely being sent as a test user?

**Comment by Edujugon** [comment]
Hi @discovery-mark ,

If `getEnv` functions returns test mode that means that the package is using all variables under config `test` key.

I would recommend to [google that error message](http://lmgtfy.com/?q=DEVELOPER_TOKEN_NOT_APPROVED).

I'm closing this issue since looks more a token issue than a package issue.

Feel free to reopen anytime.
