### ISSUE TITLE
How to install with "googleads/googleads-php-lib": "^40.0"?

### ISSUE THREAD

**Issue by imkevinabraham** [Edujugon/laravel-google-ads#43]
I have another package installed which uses "googleads/googleads-php-lib": "^40.0". How do I install Edujugon/laravel-google-ads with  "googleads/googleads-php-lib": "^40.0" instead of [37.0.0, 40.0.0]?

PS: I really like your package.

**Comment by Edujugon** [comment]
Hi @imkevinabraham ,
I will try to get some time this weekend to upgrade the "googleads/googleads-php-lib" dependency to the latest version. after that, you shouldn't have conflicts.

**Comment by imkevinabraham** [comment]
thanks @Edujugon. That would be awesome! I really like your package and want to use it in my app

**Comment by Edujugon** [comment]
Hey @imkevinabraham ,

Could you paste here the error you get when trying to install the package?

**Comment by imkevinabraham** [comment]
Hey @Edujugon 

```
$ composer require edujugon/laravel-google-ads
Using version ^1.6 for edujugon/laravel-google-ads
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install edujugon/laravel-google-ads 1.6.2
    - Conclusion: don't install edujugon/laravel-google-ads 1.6.1
    - Conclusion: remove googleads/googleads-php-lib 40.0.0
    - Installation request for edujugon/laravel-google-ads ^1.6 -> satisfiable by edujugon/laravel-google-ads[1.6.0, 1.6.1, 1.6.2].
    - Conclusion: don't install googleads/googleads-php-lib 40.0.0
    - edujugon/laravel-google-ads 1.6.0 requires googleads/googleads-php-lib ^37.0 -> satisfiable by googleads/googleads-php-lib[37.0.0, 37.1.0].
    - Can only install one of: googleads/googleads-php-lib[37.0.0, 40.0.0].
    - Can only install one of: googleads/googleads-php-lib[37.1.0, 40.0.0].
    - Installation request for googleads/googleads-php-lib (locked at 40.0.0) -> satisfiable by googleads/googleads-php-lib[40.0.0].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by Edujugon** [comment]
Hey @imkevinabraham ,

I've created a new branch that will bypass that error. My idea for the future is to remove googleads as package dependency and make the user to install it as their own dependency.

I still have to update the read me and think about how to make it as smooth as possible for future releases. So until I manage to do so I suggest you to install this package as the following:

`composer require edujugon/laravel-google-ads:"dev-feature/googleads-dev-dependency"`

**Make sure** you have `googleads/googleads-php-lib` installed as dependency or this package will fail...Anyway you don't have that problem since you already have it installed via `laravel-adwords-targeting-idea-service` package...

I will update you after the release so that you can then point to that in the future.

Let me know if that worked for you

**Comment by imkevinabraham** [comment]
@Edujugon thank you very much! this fixed the install problem.

Sounds like a great idea for a future release

**Comment by Edujugon** [comment]
Glad that helped 😊
